### ISSUE TITLE
Docker container does not catch changes made to filesystem outside of container

### ISSUE THREAD

**Issue by heywoodlh** [vrtmrz/filesystem-livesync#5]
This is totally something I can work around but I wanted to document and maybe get your input on.

When I run the Docker container the filesystem-livesync does not catch changes unless the process I use to make changes is _in the container_. For example, if I use vim or echo on my Docker host to modify files it does not catch the changes. If I use vim or echo in the container it does.

On my Mac and Linux machines I use [Lima](https://github.com/lima-vm/lima) to provide Docker functionality it might be a bug with Lima and not even related to this project. I will test and follow up.

**Comment by vrtmrz** [comment]
May be caused by misdetection of chokidar's option.
It may be solved with useFsEvent option manually, but I didn't test yet.
Coincidentally, I bought a MacBook last year, so I'm sure it will help.

Even though if it doesn't work, setting environment value “CHOKIDAR_USEPOLLING” to 1 should work.  But It may have less performance. (Poll filesystems  instead of watching native events)

**Comment by heywoodlh** [comment]
Perfect, that worked for me! Thanks. It is a bit slower but that's just fine.
